styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true

exclude_paths:
- config
- priv/repo
- priv/static
- test
